# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{io_tools}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Burnett"]
  s.date = %q{2010-08-18}
  s.default_executable = %q{io-server}
  s.description = %q{Extracted modules from the Posterous Blog Importer. Used for conforming RSS Feeds or results from one API to another.}
  s.email = %q{signalstatic@gmail.com}
  s.executables = ["io-server"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mdown",
     "Rakefile",
     "VERSION",
     "bin/io-server",
     "lib/io_tools.rb",
     "lib/io_tools/helpers.rb",
     "lib/io_tools/helpers/rss_feed.rb",
     "lib/io_tools/helpers/xml_rpc.rb",
     "lib/io_tools/importer.rb",
     "lib/server/config.ru",
     "lib/server/importers/posterous_api_importer.rb",
     "lib/server/importers/posterous_feed_importer.rb",
     "lib/server/importers/word_press_importer.rb",
     "lib/server/public/images/bg.png",
     "lib/server/public/javascripts/app.js",
     "lib/server/public/stylesheets/app.css",
     "lib/server/server.rb",
     "lib/server/views/import.haml",
     "lib/server/views/index.haml",
     "spec/io_tools/helpers/rss_feed.rb",
     "spec/io_tools/helpers/xml_rpc.rb",
     "spec/io_tools/importer_spec.rb",
     "spec/io_tools_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/posterous/io_tools}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Import framework for Blogs and Feeds}
  s.test_files = [
    "spec/io_tools/helpers/rss_feed.rb",
     "spec/io_tools/helpers/xml_rpc.rb",
     "spec/io_tools/importer_spec.rb",
     "spec/io_tools_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.2"])
      s.add_runtime_dependency(%q<feedtools>, [">= 0.2.29"])
      s.add_runtime_dependency(%q<vegas>, ["~> 0.1.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
      s.add_dependency(%q<feedtools>, [">= 0.2.29"])
      s.add_dependency(%q<vegas>, ["~> 0.1.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.2"])
    s.add_dependency(%q<feedtools>, [">= 0.2.29"])
    s.add_dependency(%q<vegas>, ["~> 0.1.2"])
  end
end

